import{a as u,i as f,S as d}from"./assets/vendor-CvstIImk.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();function y(a){const o=new URLSearchParams({q:a,key:"19790179-de8e0f050de34d9c55fd8172a",image_type:"photo",orientation:"horizontal",safesearch:!0});return u.get(`https://pixabay.com/api/?q=${o}`).then(({data:e})=>(e.hits.length||f.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"yellow"}),e.hits)).catch(e=>console.log(e))}const c=document.querySelector(".gallery"),l=document.querySelector(".loader");function m(a){const o=a.map(e=>`<li class="gallery-item">
                  <a class="gallery-link" href=${e.largeImageURL}>
                     <img class="gallery-image"
                          src="${e.webformatURL}"
                          alt="${e.tags}"
                          data-source="${e.largeImageURL}"
                          data-tags="${e.tags}" />
                  </a>
                </li>`);c.insertAdjacentHTML("beforeend",o.join("")),new d(".gallery a",{captionsData:"alt",captionDelay:250,fadeSpeed:300,overlayOpacity:.9,closeOnOverlayClick:!0,captions:!0}).refresh()}function h(){c.innerHTML=""}function g(){l.classList.add("is-shown")}function p(){l.classList.remove("is-shown")}document.querySelector('button[type="submit"]');const i=document.querySelector(".form");i.addEventListener("submit",a=>{a.preventDefault();const e=new FormData(i).get("search-text").trim();e&&(h(),g(),y(e).then(s=>{m(s),i.reset()}).finally(()=>{p()}))});
//# sourceMappingURL=index.js.map
