import{a as d,S as m,i as c}from"./assets/vendor-CesYmgD5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function y(s){const o=new URLSearchParams({q:s,key:"19790179-de8e0f050de34d9c55fd8172a",image_type:"photo",orientation:"horizontal",safesearch:!0});return d.get(`https://pixabay.com/api/?q=${o}`).then(({data:t})=>t.hits)}const u=document.querySelector(".gallery"),f=document.querySelector(".loader");function p(s){const o=s.map(t=>`<li class="gallery-item">
                  <a class="gallery-link" href=${t.largeImageURL}>
                     <img class="gallery-image"
                          src="${t.webformatURL}"
                          alt="${t.tags}"
                          data-source="${t.largeImageURL}"
                          data-tags="${t.tags}" />
                  </a>
                </li>`);u.insertAdjacentHTML("beforeend",o.join("")),new m(".gallery a",{captionsData:"alt",captionDelay:250,fadeSpeed:300,overlayOpacity:.9,closeOnOverlayClick:!0,captions:!0}).refresh()}function g(){u.innerHTML=""}function h(){f.classList.add("is-shown")}function L(){f.classList.remove("is-shown")}const l=document.querySelector('button[type="submit"]'),i=document.querySelector(".form");i.addEventListener("submit",s=>{s.preventDefault();const t=new FormData(i).get("search-text").trim();t&&(g(),h(),y(t).then(a=>{if(a.length===0){c.show({color:"yellow",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(a),i.reset(),l.disabled=!0}).catch(a=>c.error({color:"red",message:a.message,position:"topRight"})).finally(()=>{L(),l.disabled=!1}))});
//# sourceMappingURL=index.js.map
